#! /bin/bash

rsync $* --filter="+ /base/" --filter="+ /software/" --filter="+ /templates/" --filter="- /templates/tp/" --filter="- /*" --checksum --delete -imrv ./ /dls_sw/dasc/static_pages/buckminster/
